= Zipkin Forwarder

Zipkin forwarder is a span forwarder service to ship spans between multiple data center. The main
motivation behind this is to transport spans from cross data center and hybrid cloud
setup and store them in a single place for analysis.

It collects spans via HTTP transport and accepts zipkin v1 and v2 JSON formats and forwards to
different Zipkin Collectors

Limitations: It is designed to work as a proxy for spring cloud sleuth and other encodings will
be supported if required

== Running the service

Clone the repository and run `mvn clean spring-boot:run`

Provide the configuration in the `application.properties file`

== Zipkin Collectors

*Current Status:*

  * Supports AWS Kinesis as the middleware needs Zipkin Kinesis Collector to collect the spans
  * Supports Forwarding to Zipkin Http Collectors
  * Supports Forwarding to GCP Stackdriver

*Future Work:*
Support for Zipkin-GCP pub/sub, Kafka, RabbitMQ and Zipkin-Azure

== LICENSE

Copyright 2018 Ascend Corporation (https://www.ascendcorp.com/)

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License
is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
or implied. See the License for the specific language governing permissions and limitations under
the License.