= Zipkin Forwarder

Zipkin forwarder is a span forwarder service to ship spans between multiple data center. The main
motivation behind this is to transport spans from cross data center and hybrid cloud
setup and store them in a single place for analysis.

It collects spans via HTTP transport and forwards to different Zipkin Collectors

== Running the service

Clone the repository and run `mvn spring-boot:run`

== Zipkin Collectors

*Current Status:* Only supports AWS Kinesis as the middleware needs Zipkin Kinesis Collector to
collect
the spans

*Future Work:*
Support for Zipkin-GCP, Zipkin-Azure and Http Collectors
Move collectors to auto configuration

== LICENSE

Copyright 2018 Ascend Corporation (https://www.ascendcorp.com/)

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License
is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
or implied. See the License for the specific language governing permissions and limitations under
the License.